In [19]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [20]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [21]:
math.log(32, 2)

5.0

In [22]:
import math as mt
mt.pi

3.141592653589793

In [23]:
import math
mt = math

In [24]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [25]:
from math import log, pi
from numpy import asarray

In [26]:
# Roll 10 dice
import numpy
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([3, 3, 5, 3, 2, 4, 5, 2, 5, 4])

In [27]:
type(rolls)

numpy.ndarray

In [28]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [29]:
# If I want the average roll, the "mean" method looks promising...
rolls.mean()

3.6

In [30]:
# Or maybe I just want to turn the array into a list, in which case I can use "tolist"
rolls.tolist()

[3, 3, 5, 3, 2, 4, 5, 2, 5, 4]

In [31]:
# That "ravel" attribute sounds interesting. I'm a big classical music fan.
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [36]:
# Cannot: [3, 4, 1, 2, 2, 1] + 10

In [33]:
rolls + 10

array([13, 13, 15, 13, 12, 14, 15, 12, 15, 14])

In [34]:
# At which indices are the dice less than or equal to 3?
rolls <= 3

array([ True,  True, False,  True,  True, False, False,  True, False,
       False])

In [35]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]
